/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package companydbmanagerant.view.Main;

import com.formdev.flatlaf.FlatClientProperties;
import com.formdev.flatlaf.ui.FlatUIUtils;
import companydbmanagerant.model.Department.Department;
import companydbmanagerant.model.Employee.Employee;
import companydbmanagerant.model.TableModel.AllEditTableModel;
import companydbmanagerant.model.TableModel.SortByTableModel;
import companydbmanagerant.view.DataViewUtil;
import java.math.BigDecimal;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.List;
import javax.swing.JOptionPane;
import raven.toast.Notifications;

import java.awt.Color;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.util.ArrayList;
import javax.swing.JComboBox;
import javax.swing.JComponent;
import javax.swing.JTextField;
import javax.swing.border.LineBorder;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author PHC
 */
public class SortByPanel extends javax.swing.JPanel {

    SortByTableModel sortByTableModel;

    /**
     * Creates new form EmployeeEditPanel
     */
    public SortByPanel(SortByTableModel sortByTableModel) {
        initComponents();

        this.sortByTableModel = sortByTableModel;
        EmployeeTable.setModel(sortByTableModel);
        jButton3.setEnabled(false);
        jButton4.setEnabled(false);
        jButton5.setEnabled(false);
        jButton6.setEnabled(false);
        jButton7.setEnabled(false);

        setTableListener();
//        this.departments = departments;
        jButton1.setName("exitBtnCircle");
//        // TextField와 ComboBox에 Employee 객체의 값을 설정
//        jButton2.setEnabled(false);
//        jButton2.setName("executeBtn");
//        addComboListeners();
//        init();
        //setDepartmentCombo();
//        setSuperSSNCombo();
//        setEmployeeValues();
    }

    private void setTableListener() {
        // 테이블의 selection 모델에 대한 ListSelectionListener 추가
        EmployeeTable.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                // getValueIsAdjusting는 이벤트가 한 번만 처리되도록 해줌
                if (!e.getValueIsAdjusting()) {
                    // 선택된 행의 개수 확인
                    int[] selectedRows = EmployeeTable.getSelectedRows();

                    // 선택된 행이 정확히 하나일 경우 버튼을 활성화
                    boolean enableButtons = selectedRows.length == 1 || selectedRows.length == 0;
                    jButton3.setEnabled(enableButtons);
                    jButton4.setEnabled(enableButtons);

                    if (selectedRows.length == 1) {

                        if (selectedRows[0] == 0) {
                            jButton3.setEnabled(false);
                        }
                        if (selectedRows[0] == sortByTableModel.getRowCount() - 1) {
                            jButton4.setEnabled(false);
                        }
                        int noneindex = sortByTableModel.findNone();
                        if (noneindex != -1 && noneindex <= selectedRows[0]) {
                            jButton3.setEnabled(false);
                        }
                        if (noneindex != -1 && noneindex <= selectedRows[0] + 1) {
                            jButton4.setEnabled(false);
                        }
                    }

                    boolean enableButtons2 = selectedRows.length != 0;
                    jButton5.setEnabled(enableButtons2);
                    jButton6.setEnabled(enableButtons2);
                    jButton7.setEnabled(enableButtons2);
                }
            }
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        EmployeeTable = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();

        jButton1.setText("X");

        jLabel7.setFont(new java.awt.Font("맑은 고딕", 0, 14)); // NOI18N
        jLabel7.setText("정렬 기준 설정");

        jButton3.setText("↑");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        EmployeeTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "정렬우선순위", "Column명", "ASC/DSEC/NONE"
            }
        ));
        jScrollPane1.setViewportView(EmployeeTable);

        jButton4.setText("↓");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("SET ASC");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("SET DSEC");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("SET NONE");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
                            .addComponent(jButton7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(11, 11, 11))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1)
                        .addGap(34, 34, 34)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton7)
                        .addGap(0, 140, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        int[] selectedRows = EmployeeTable.getSelectedRows();
        if (selectedRows.length == 1) {
            boolean success = sortByTableModel.upper(selectedRows[0]);

            sortByTableModel.refreshOrder();
            sortByTableModel.fireTableDataChanged();
            if (success) {
                EmployeeTable.setRowSelectionInterval(selectedRows[0] - 1, selectedRows[0] - 1);
            }
        }

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        int[] selectedRows = EmployeeTable.getSelectedRows();
        if (selectedRows.length == 1) {
            boolean success = sortByTableModel.downner(selectedRows[0]);

            sortByTableModel.refreshOrder();
            sortByTableModel.fireTableDataChanged();
            if (success) {
                EmployeeTable.setRowSelectionInterval(selectedRows[0] + 1, selectedRows[0] + 1);
            }

        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        int[] selectedRows = EmployeeTable.getSelectedRows();
        for (int i : selectedRows) {
            sortByTableModel.setValueAt("ASC", i, 2);
        }
        sortByTableModel.refreshOrder();
        sortByTableModel.fireTableDataChanged();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        int[] selectedRows = EmployeeTable.getSelectedRows();
        for (int i : selectedRows) {
            sortByTableModel.setValueAt("DESC", i, 2);
        }
        sortByTableModel.refreshOrder();
        sortByTableModel.fireTableDataChanged();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        int[] selectedRows = EmployeeTable.getSelectedRows();
        for (int i : selectedRows) {
            sortByTableModel.setValueAt("NONE", i, 2);
        }
        sortByTableModel.refreshOrder();
        sortByTableModel.fireTableDataChanged();
    }//GEN-LAST:event_jButton7ActionPerformed
//    private void tableUpdate() {
//        JComboBox fieldCombo = comboBox1;
//        JComboBox operationCombo = comboBox2;
//        JComboBox valueOptionsComboBox = comboBox3;
//        JTextField valueField = textField1;
//        String selectedItem = comboBox1.getSelectedItem().toString();
//        boolean isUseCombo = ("Sex".equals(selectedItem) || "Dname".equals(selectedItem) || "Super_ssn".equals(selectedItem));
//
//        String field = fieldCombo.getSelectedItem().toString();
//        String operation = operationCombo.getSelectedItem().toString();
//        String value = "";
//        if (isUseCombo) {
//            Object Item = valueOptionsComboBox.getSelectedItem();
//            if (Item != null) {
//                value = Item.toString();
//            } else {
//                value = "";
//            }
//        } else {
//            value = valueField.getText();
//        }
//        allEditTableModel.callTableUpdate(field, operation, value);
//        allEditTableModel.fireTableDataChanged();
//
//    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable EmployeeTable;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
